---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - redis-deployment.yaml
  - redis-service.yaml
  - guestbook-deployment.yaml
  - guestbook-service.yaml
  - guestbook-ingress.yaml
