---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
- name: gitlab-registry.trusting-bunny.commandemy.training/git-user-01/guestbook-application
  newTag: "1" # {"$imagepolicy": "flux-system:guestbook:tag"}

