---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
- name: gitlab-registry.<ENV-GITLAB-DOMAIN>/git-user-<ENV-USER-ID>/guestbook-application
  newTag: "1" # {"$imagepolicy": "flux-system:guestbook:tag"}

